### ISSUE TITLE
Modifying config.js has no effect

### ISSUE THREAD

**Issue by slawkor** [evoluteur/evolutility-ui-jquery#15]
How exactly do you configure the use of REST? Modifying config.js as follows has no effect for me.

```
var Evol = Evol || {};

Evol.Config = {

	// --- using localStorage
	localStorage: false,

	// --- using evolutility-server-node
	url: 'http://localhost:3000/api/v1/evolutility/',

	// --- using postgrest
	//url: 'http://localhost:3001/'
};
```

**Comment by slawkor** [comment]
Looks like the actual config is made in [evolutility-ui-jquery.js](https://github.com/evoluteur/evolutility-ui-jquery/blob/a9eb6122d595e6b7235533fa287c19a99c31e023/dist/evolutility-ui-jquery.js) plus [config.js](https://github.com/evoluteur/evolutility-ui-jquery/blob/a9eb6122d595e6b7235533fa287c19a99c31e023/config.js) is not included anywhere. Is this by design?

**Comment by evoluteur** [comment]
You must run grunt to rebuild the files evolutility-ui-jquery.js (or evolutility-ui-jquery.min.js). These files include the config.js.

**Comment by slawkor** [comment]
Thanks, the grunt dev task did the trick.

**Comment by evoluteur** [comment]
Thanks for letting me know. I updated the ReadMe file.
