### ISSUE TITLE
Error in grunt

### ISSUE THREAD

**Issue by wolfhear7ed** [evoluteur/evolutility-ui-jquery#17]
Hi,

We're trying integrating the jquery-front-end with the server node. We are getting the following error message, we try to force the grunt but the front-end is not working properly.

![image](https://user-images.githubusercontent.com/4984880/34955087-b4a363be-fa01-11e7-9eba-843e22454e46.png)

Really appreciate your help.
Best regards.
Julio.-

**Comment by evoluteur** [comment]
Run bower first w/ "bower install".
