### ISSUE TITLE
Editing URL fields and upload images

### ISSUE THREAD

**Issue by marcomarsala** [evoluteur/evolutility-ui-jquery#18]
These feature are not implemented yet? I'm seeing the Wine Cellar demo.

**Comment by evoluteur** [comment]
Upload images is implemented.
I'm not sure about what you mean by "Editing URL fields".

**Comment by evoluteur** [comment]
Sorry, I have no plan to implement it right now.
I'm working on Evolutility-UI-React which has the upload image feature you would like.
