### ISSUE TITLE
How do I change the data type？like a: "644488000.0000" ---->a:644488000.0000

### ISSUE THREAD

**Issue by blueandandsky** [evoluteur/evolutility-ui-jquery#20]
Hi!
I use evolutility-server-node and evolutility-ui-jquery.
The project is set up, but there are problems when filtering is used.
I need to filter the data based on the size of the number, but the browser gets the data in the form of a string, not a number.
I tried to solve it, but failed.
``` 
               #  evolutility-server-node/models/organizer/test.js
                {
			"id": "a",
			"type": "decimal",
			"inMany": true,
			"column": "a"
		}
              # evolutility-ui-jquery/models/test.js
               {
                    id: 'a', 
                   attribute: 'a', 
                   type: 'decimal',
                   label:'a', 
                   inMany: true,                 
                }

**Comment by evoluteur** [comment]
That should fix it: https://github.com/evoluteur/evolutility-ui-jquery/commit/1d28742ac885304955909585bd1d03f3274dd971#diff-32981a13284db7a021131df49e6cd203
